version: 2

jobs:
  build:
#    machine:
#      java:
#        version: oraclejdk8
#      python:
#        version: 2.7.10
    docker:
      - image: circleci/android:api-26-alpha
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: pre-dependencies
          command: pip install --user codecov
      - run: sdkmanager --licenses
      - run:
          name: override-test
          command: ./gradlew --info install test coverage
      - run:
          name: post-test
          command: node_modules/codecov/bin/codecov

