version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: pre-dependencies
          command: sudo pip install codecov
      - run: sdkmanager --licenses
      - run:
          name: override-test
          command: ./gradlew --info install test coverage
      - run:
          name: post-test
          command: codecov