version: 2

jobs:
  build:
#    machine:
#      java:
#        version: oraclejdk8
#      python:
#        version: 2.7.10
    docker:
      - image: circleci/android:api-26-alpha
      - image: circleci/python:2.7.10
    steps:
      - checkout
      - run:
          name: pre-dependencies
          command: pip install codecov
      - run: sdkmanager --install "ndk-bundle"
      - run: sdkmanager --licenses
#      - run:
#          name: override-dependencies
#          command: echo y | android update sdk --no-ui --all --filter build-tools-26.0.2,android-26




test:
  override:
  - ./gradlew --info install test coverage
  post:
  - codecov

